name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'dist/**'
      - 'invoke-binary.js'
  pull_request:
    branches: [main]

jobs:
  unit-tests-and-build:
    name: lint, unit tests & build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run unit tests
        uses: ./.github/actions/unit-tests
        with:
          coveralls-token: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.COVERALLS_REPO_TOKEN || '' }}
      
      - name: Build application  
        run: make build-linux-amd64
