name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'dist/**'
      - 'invoke-binary.js'
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: lint & unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run unit tests
        uses: ./.github/actions/unit-tests
        
      - name: Publish coverage
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/publish-coverage
        with:
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Build application
        run: make build-linux-amd64
