name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'dist/**'
      - 'invoke-binary.js'
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: lint & unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      
      - name: Run unit tests
        uses: ./.github/actions/unit-tests
        
      - name: Upload coverage artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1

  publish-coverage:
    name: publish coverage
    runs-on: ubuntu-latest
    needs: unit-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      
      - name: Download coverage artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 #v6.0.0
        with:
          name: coverage-report
          
      - name: Publish coverage
        uses: ./.github/actions/publish-coverage
        with:
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c #v6.1.0
        with:
          go-version: 1.25

      - name: Build application
        run: make build-linux-amd64
