name: PR Reminder

on:
  workflow_dispatch:
    inputs:
      run-mode:
        description: 'Run mode'
        type: choice
        options:
          - post
          - update
        required: true
      build-first:
        description: 'Build the project first'
        type: boolean
        default: false
        required: false
  schedule:
    - cron: '0 9 * * 0-6'  # at 09:00 every day
  pull_request:
    types: [closed, ready_for_review]
  pull_request_review:
    types: [submitted]
  issue_comment:
  push:
    branches: [main]

jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Build application
        if: inputs.build-first
        uses: ./.github/actions/build

      - name: Send PR reminder
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.DEV_SLACK_TOKEN }}
          run-mode: ${{ (github.event_name == 'schedule' || inputs.run-mode == 'post') && 'post' || 'update' }}
          slack-channel-name: github
          github-user-slack-user-id-mapping: |
            hellej: U08SZJTJF0U
            bob: U08EVPGNWER
      
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
        with:
          name: pr-slack-reminder-state
          path: pr-slack-reminder-state.json
          retention-days: 1
